### ISSUE TITLE
Please add setup script for new users that includes required development packages

### ISSUE THREAD

**Issue by ZotZotZeta** [FlyingRhenquest/fr_events#2]
Was missing GIT, Boost, pkg-config, build-essential, cmake

**Comment by FlyingRhenquest** [comment]
I added an extras directory with a setup script that should work on ubuntu-derived systems (And probably generic debian too,) along with a docker file so that I could test the setup script on an incredibly barebones ubuntu install. There are some instructions in that directory. The "ubuntish.sh" script should install the dev environment for you. Please review the script prior to running it, as it's calling sudo to install packages, make sure it's not doing anything you don't want it to. The build.sh script briefly illustrates how to build the library, run the unit tests and the python example program.

I'll close this issue for now. Please feel free to reopen it if that solution was not adequate, or open a new issue if you have feature requests or run across bugs with this solution.
